CDCgov/RecordLinker

.github/workflows/check_unit_tests.yml
pyproject.toml

The latest version of pyway, 0.3.30, is not able to read the existing migrations directory.  Since these migrations are deprecated in favor of alembic, the easiest path forward is to pin pyway to version 0.3.29 until its removed from the project.
Within #19 we simplified the settings to use the new DB_URI env variable to define connection settings.  We forgot to also update update postgres database setup in the GH testing workflow to follow this pattern.

update GH unit test workflow DB

---

src/recordlinker/linkage/matchers.py
tests/unit/test_linkage.py
tests/unit/test_matchers.py
tests/unit/test_record_linkage.py

* Normalize `birthdate` type of an existing Patient record from `datetime.time` to `str` upon match evaluation, before comparing with `birthdate` of an incoming Patient record.
* Closes #17 
Initially, two of the unit tests failed as a result of the new logic after resolving the bug. By logging the similarity scores & match decisions, I understood why the tests were wrongfully succeeding previously. To address this, I changed the expected results of these two tests, rather than change the FHIR bundle of test cases itself, to avoid downstream test failure where this bundle is used elsewhere.
In the future, we should normalize `birthdate` type elsewhere, and only once. Currently, this `datetime.time` to `str` type conversion happens several places. This can be done more DRYly, and any data …

fix(match): normalize DOB type

---

src/recordlinker/linking/link.py
src/recordlinker/models/algorithm.py
src/recordlinker/utils.py
tests/unit/models/test_algorithm.py
tests/unit/test_utils.py

Adds the `bound_evaluators` and `bound_rule` functions to the AlgorithmPass model so we can cache the binding operations for future use.
This is a small optimization for features added in #72 
Binding the AlgorithmPass evaluators and rule to functions for every compare call adds overhead.  It's quicker if we just do that once for the pass, and allow all subsequent calls to reuse the bound values.

Optimizing initialization of evaluators and rule

---

.github/workflows/slack_notifier_open_pulls.yml

Fixing the slack notifier open pulls workflow to run on a schedule in main.  The `if: ${{ env.PR_LIST != '[]' }}` comparison is too complex for a GH action step, we need to simplfy that a bit by doing more logic in the proceeding step.

fix slack notifier open pulls

---

src/recordlinker/config.py
src/recordlinker/models/algorithm.py
src/recordlinker/models/base.py
src/recordlinker/models/mpi.py

Adding `setting.db_table_prefix` so customers can optionally change all the table names with a prefix.
Allowing customers to use an existing database for storing the MPI tables comes at a risk of not knowing what existing tables the customer might have in their database.  To guarantee that the customer doesn't have any naming conflicts with the tables created by Record Linker, we can allow for an optional prefix ENV variable given them the opportunity to override the table names.

add setting.db_table_prefix variable

---

docs/process_for_adding_feature.md
src/recordlinker/linking/link.py
src/recordlinker/linking/matchers.py
src/recordlinker/schemas/pii.py
tests/unit/linking/test_link.py
tests/unit/schemas/test_pii.py

NBS has requested that we add additional fields for feature comparisons. We won't need to block on any of these features, but we do need to have the ability to compare them in the second half of the algorithm.
closes #55 
HL7 FHIR resources
- https://build.fhir.org/patient-examples-general.json.html 
- https://hl7.org/fhir/R5/patient.html
- https://hl7.org/fhir/R5/datatypes-examples.html#HumanName
- https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-race.html
- https://www.hl7.org/fhir/us/core/Patient-example.json.html

Expand Feature Comparison Support

---

docs/mpi-design.md
src/recordlinker/linking/mpi_service.py
src/recordlinker/main.py
src/recordlinker/models/mpi.py
src/recordlinker/routes/patient_router.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/mpi.py
tests/unit/linking/test_mpi_service.py
tests/unit/routes/test_patient_router.py

Adding two new endpoints to support updating the Person cluster a Patient belongs to.  One is for assigning the Patient to a specific cluster, and another is for assigning them to a new cluster.
closes #96 
- `POST /patient/<ref-id>/person` takes an empty payload, creates a new Person cluster, assigns the Patient to that cluster and returns back reference ids for both the Patient and Person.
- `PATCH /patient/<ref-id>/person` takes a person ref id payload, assigned the Patient to that existing Person and returns back reference ids for both the Patient and Person.
Please review and complete the following checklist during …

endpoints to update person cluster on patient

---

docs/process_for_adding_feature.md
src/recordlinker/hl7/fhir.py
src/recordlinker/linking/link.py
src/recordlinker/routes/link_router.py
tests/unit/hl7/test_fhir.py
tests/unit/linking/test_link.py
tests/unit/routes/test_link_router.py

Abstract the parsing of FHIR out into its own module, as the linking algorithm should be input format agnostic. This approach will let us expand our supported formats for ELR and eCR ahead.
closes #80 
- creates `recordlinker.parsers.fhir`
- add new `link/fhir` endpoint that accepts `fhir` bundles but response similar to the `/link` endpoint
- add tests for new endpoint and new test file for `fhir` parser

Create New Parsers Framework

---

src/recordlinker/hl7/fhir.py
src/recordlinker/schemas/pii.py
tests/unit/hl7/test_fhir.py
tests/unit/schemas/test_pii.py

Add a new Feature to run comparisons on driver's license numbers.
closes #95 

Drivers License Feature

---

.github/workflows/check_smoke_tests.yml
src/recordlinker/hl7/fhir.py
src/recordlinker/linking/algorithm_service.py
src/recordlinker/routes/link_router.py
tests/performance/scripts/reset_db.sh
tests/performance/scripts/send_linkage_requests.sh
tests/unit/linking/test_algorithm_service.py
tests/unit/routes/test_link_router.py

Create a new CI workflow that runs a smoke test job when a PR is open.
closes #103 
The smoke test should roughly do the following, but more steps can be added if identified during the development process
- start up a database
- build the Dockerfile
- run the RL service on the docker container
- send a series (~4 or so) of curl requests to the /link endpoint, and verify results

Dockerfile Smoke Tests

---

.github/workflows/check_smoke_tests.yml
src/recordlinker/assets/initial_algorithms.json
src/recordlinker/database/mpi_service.py
src/recordlinker/linking/link.py
src/recordlinker/models/algorithm.py
src/recordlinker/models/mpi.py
src/recordlinker/routes/link_router.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/algorithm.py
src/recordlinker/schemas/link.py
tests/unit/assets/multiple_matches_patient_bundle.json
tests/unit/assets/possible_match_basic_patient_bundle.json
tests/unit/assets/possible_match_enhanced_patient_bundle.json
tests/unit/database/test_algorithm_service.py
tests/unit/database/test_mpi_service.py
tests/unit/linking/test_link.py
tests/unit/models/test_algorithm.py
tests/unit/routes/test_algorithm_router.py
tests/unit/routes/test_link_router.py
tests/unit/schemas/test_algorithm.py

* Implement Possible Match using short-term approach: Apply a user-configurable range to the Belongingness Ratio threshold.
* To support Possible Match, update Link API response as follows:
**Example:** `belongingness_ratio=[0.75, 0.9]`
**No Match**
```
{
"patient_reference_id": "5a12bf00-16f8-4c03-b980-81d3f5ff6db6",
"person_reference_id": "b104942e-6327-4643-801a-5fb22cb621c4", # New Person ID
"results": []
}
```
**Possible Match**
```
{
"patient_reference_id": "c5fcfc39-a915-4b65-afc7-b681c892652e",
"person_reference_id": None,
"results": [
{
"person_reference_id": "bf27f9f2-2882-4e6f-9db9-6a916679cff7",
"belongingness_ratio": 0.8
}
]
}
```
**Match** `include_multiple_matches=false`
```
{
"patient_reference_id": "2eb14d86-217f-45c3-a528-d038e7eadce7",
"person_reference_id": …
```

feat(linking): implement possible match short-term

---

docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/database/test_mpi_service.py
tests/unit/linking/test_matchers.py
tests/unit/schemas/test_pii.py

Renaming `Feature.TELEPHONE` to `Feature.TELECOM`, as that more accurately describes the matching behavior.  Adding` Feature.GIVEN_NAME` and updating `Feature.FIRST_NAME` to only use the first element of a given name.
closes #128
closes #129 
- TELEPHONE was misleading because the telecom field could collect emails, fax numbers and other contact points, that would be included in the matches.  Renaming this to TELECOM better explains to the user what we're matching on.
- FIRST_NAME was misleading, as it was including the middle names in its matches as well.
Please review and complete the following checklist during the …

fix misleading matcher names

---

src/recordlinker/database/mpi_service.py
src/recordlinker/models/mpi.py
src/recordlinker/schemas/pii.py
tests/unit/database/test_mpi_service.py
tests/unit/routes/test_seed_router.py

Data can be inserted when linking or seeding, in the former we were inserting the data as a dictionary into the Patient.data column, however in the latter we inserted the data as a string.  This causes issues on subsequent reads when using the data.
The call to convert the PIIRecord into a value for the database has been standardized in PIIRecord.to_dict(), and the bulk insert method (which is used in the seeding process) has been updated to use this method.

bugfix: bulk insert serialization of data

---

src/recordlinker/database/mpi_service.py
src/recordlinker/routes/patient_router.py
tests/unit/routes/test_patient_router.py

Mistakes can happen, and there could be times when customers send a record to the link API by mistake (could be a known duplicate document, or just an error in the workflow). We should have the ability to "undo" those mistakes. Create a new DELETE /patient/<patient_reference_id> endpoint that will allow users to remove a known patient record.
closes #138 

Ability to delete a Patient record

---

.env
.github/workflows/check_unit_tests.yml
.gitignore
README.md
pyproject.toml
scripts/bootstrap.sh
src/recordlinker/config.py
src/recordlinker/database/__init__.py
tests/unit/database/test_base.py

Removing the git controlled `.env` file and automating the dev setup process with `scripts/bootstrap.sh`.
Developers should be able to customize the .env file to their environment, and not have to worry about it changing whenever they pull new code.  To make the developer setup process easy, the new bootstrap script will create a .env file if it doesn't exist, initialize a virtual environment if it doesn't exist, activate the virtual env and install the development python requirements.
- Connection pooling parameters now have their default values set to None, so it will work with sqlite:///:memory:
- The sessionmaker autocommit parameter was removed in sqlalchemy 2.0
Please review and complete the …

bootstap script

---

pyproject.toml

Version 3.1.0 of this library has renamed some modules that are causing import errors
https://github.com/nhairs/python-json-logger/releases/tag/v3.1.0

Fix: pin pythonjsonlogger to 2.X.X

---

.github/workflows/release.yml

The .env no longer exists in the repo, so we must manually set a value for the required DB_URI
Example build failure https://github.com/CDCgov/RecordLinker/actions/runs/12319787147/job/34387640857

Fix: adding DB_URI var when building docs in release

---

.github/workflows/check_smoke_tests.yml
Dockerfile

Corrects the syntax of the if block in the Dockerfile to ensure proper evaluation for installing msodbcsql18 and unixodbc-dev. This fix resolves an issue where the Record Linker image fails to start when configured with a sqlserver DB_URI.
This is a significant issue for users who want to: a) use our published Docker images on ghcr.io and b) connect to a sqlserver database. The if block on line 30 of the Dockerfile has syntax that works with /bin/bash but not with /bin/sh. As a result, the step was always skipped during the image build process.
This update introduces a database matrix to our smoke tests, enabling the Docker image to be tested against all four supported databases, not just PostgreSQL. …

fix: docker builds with libodbc

---

.github/workflows/check_lint.yml
.github/workflows/release.yml

Fix for the calculation of the draft variable in the release workflow.
closes #180 
Some testing code was added to a previous commit, 5a3dff6, then removed once the new if block was [verified to work](https://github.com/CDCgov/RecordLinker/actions/runs/12942197619/job/36099510623).  See the additional context in the linked issue for more context on why the fix should work.

fix: release draft variable

---

README.md

This PR adds a brief note about running the bootstrap script on a Windows machine. Due to how WSL can be configured on a Windows machine, users may wish to ignore the directory changing OR configure the repo in the Ubuntu directory of their machine in order for the script to run.
n/a
RecordLinker had not been tested on a Windows machine

Update README with note about running on Windows

---

docs/site/reference.md
scripts/gen_seed_test_data.py
src/recordlinker/hl7/fhir.py
src/recordlinker/schemas/pii.py
tests/unit/hl7/test_fhir.py
tests/unit/models/test_mpi.py
tests/unit/schemas/test_pii.py

Removing the Gender matching field per [Executive Order 14168](https://www.chcoc.gov/content/initial-guidance-regarding-president-trump%E2%80%99s-executive-order-defending-women).

Remove Gender matching Feature [Executive Order 14168]

---

docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/routes/test_seed_router.py
tests/unit/schemas/test_pii.py

Removing the Sex.UNKNOWN value per [Executive Order 14168](https://www.chcoc.gov/content/initial-guidance-regarding-president-trump%E2%80%99s-executive-order-defending-women).

removing Sex.UNKNOWN [Executive Order 14168]

---

src/recordlinker/database/mpi_service.py
src/recordlinker/routes/patient_router.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/mpi.py
tests/unit/database/test_mpi_service.py
tests/unit/routes/test_patient_router.py

Add two new API endpoints that allow users to directly add/update patient record details in the MPI.
closes #159 
`POST /patient -d '{"record": "...", "person": "person_reference_id"}'`
Add the above endpoint to allow users to directly add a patient record to the MPI, skipping the record linkage algorithm.
`PATCH /patient/<patient-reference-id> -d '{"record": "...", "person": "person_reference_id"}'`
Add the above endpoint to allow users to update an existing patient record in the MPI.
NOTE: For this operation, the `record` and `person` attributes are optional.  If not specified, the existing value will stay unchanged.  However, at least 1 must be specified.
Please review and complete the following …

Patient Details Endpoints

---

pyproject.toml

When we install RecordLinker into an environment, a version number is automatically calculated from git data using setuptools scm. If the HEAD is a version tag, then the version is automatically calculated to be that.  In development environments, though, we take the last version and add a "post.0" to it, showing it's a new release post the last named one.
Additionally, we were previously calculating a timestamp to add to that "post.0" value based on when HEAD was committed.  This worked most of the time, however if the developer has a dirty index, the wheel wouldn't build correctly.  We don't need that, and it's fine if a developer tries to install / reinstall RecordLinker in an environment with a dirty index. So to get around that, we'll stop adding the timestamp to the end of "post.0" …

new local scheme of dirty-tag for developer installation

---

Dockerfile

msodbc18 can now be installed on ARM64 (eg Mac M1) platforms so we can remove the if block in the Dockerfile to exclude this process for those platforms.
#184 
I'm not sure if we have a good way to test the success of this change but if I followed the Teams conversation correctly, we have confirmed that NBS was able to get this working.

Build msodbc drivers into arm64 images

---

docs/site/reference.md
src/recordlinker/models/mpi.py
src/recordlinker/schemas/algorithm.py

Small updates to the existing BlockingKey descriptions and changing the schema to include the description as well as the value when rendering the information in `GET /openapi.json`
closes #187 

Add BlockingKey descriptions to openapi.json

---

src/recordlinker/schemas/pii.py
tests/unit/schemas/test_pii.py

This PR removes the `feature_iter` yield for the `RACE` field whenever an incoming record has a value for that field of `UNKNOWN` or `ASKED_UNKNOWN`. This ensures that, downstream, we don't perform fuzzy string comparisons against known race values and `UNKNOWN` and thereby award some log odds points where none should be.
#193 
n/a

Appropriately handle race unknown

---

src/recordlinker/schemas/pii.py
tests/unit/schemas/test_pii.py

Since Jaro-Winkler is the default similarity measure for string comparisons, more weight is given to differences at the start of a string. As such, this PR modifies the way that we yield and store Identifiers for comparison. Previously, the Identifier format was `type:authority:value` but now it is `value:authority:type` to give more weight to the value. For example, when comparing two MRNs with values, `1234` and `2345`, we will now give more weight to `1234` vs `2345` than the type, e.g., `MR` vs `MR`. This should yield better differentiation between strings.
Fixes #200 
I updated the language in the RFC to reflect the new format and added a note at the bottom to indicate that the RFC has been changed.

Reverse identifiers for comparisons

---

docs/site/reference.md
src/recordlinker/linking/matchers.py
tests/unit/linking/test_matchers.py

This PR adds a matcher function for evaluating a probabilistic exact match. For a given feature field in two patient records, the matcher awards maximum log odds points for that field if the two fields are exactly the same and 0 points otherwise.
#201

Create function for probabilistic exact match

---

docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/linking/test_matchers.py
tests/unit/schemas/test_pii.py

When comparing given name values, we should concatenate the entire given name before evaluation. Not doing so runs a risk of obtaining a high score when only the middle names/initials match.
closes #199 

compare the entire GIVEN_NAME

---

src/recordlinker/database/mpi_service.py
src/recordlinker/routes/patient_router.py
src/recordlinker/routes/person_router.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/mpi.py
tests/unit/conftest.py
tests/unit/database/test_mpi_service.py
tests/unit/routes/test_patient_router.py
tests/unit/routes/test_person_router.py

Creating `GET /person/<ref-id>` and `GET /patient/<ref-id>` to retrieve info on the existing MPI data elements.
closes #162 
Adding a testing helper context manager to count database queries, hoping this can be useful when we want to make assertions on how many SQL queries are issued.

patient / person API endpoints for retrieving data

---

docs/api_template.hbs
scripts/build_docs.sh

Developing a custom Handlebars template for Redoc to generate API documentation. This template enables us to override CSS rules and execute JavaScript functions to modify HTML tag attributes, aiming to resolve known accessibility (a11y) issues.
closes #198 
Using [axe devtools](https://www.deque.com/axe/devtools/) to identify and help correct known a11y issues.  These changes have resolved all known serious, critical, moderate and minor issues according to axe.

add custom api docs template to address a11y issues

---

src/recordlinker/routes/patient_router.py
tests/unit/routes/test_patient_router.py

Removes deprecated API endpoints in `/patient` now that they have been replaced by endpoints in the `/person` router.
Fixes #160

removes deprecated API endpoints

---

src/recordlinker/database/mpi_service.py
src/recordlinker/routes/person_router.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/mpi.py
tests/unit/database/test_mpi_service.py
tests/unit/routes/test_person_router.py

This PR adds an API endpoint for deleting persons who have no associated patients. It works by checking that the provided person_reference_id is valid and then checking if the person has any associated patients. Persons with associated patients are not deleted. 
Addresses 1 of the 3 API endpoints listed in #163
The other API endpoints in #163 will be in follow-up PRs.

Add endpoint for deleting orphaned persons

---

docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/schemas/test_pii.py

Changing IDENTIFIER blocking keys to `{value[-4:]}:{type}` format, authority is no longer present in the keys.
BREAKING CHANGE: The format of IDENTIFIER blocking keys has changed, and databases should be reset before upgrading.
closes #226 

Removed first 2 chars of authority from IDENTIFIER blocking key

---

src/recordlinker/database/mpi_service.py
tests/unit/assets/possible_match_default_patient_bundle.json
tests/unit/database/test_mpi_service.py

This PR adds a filter function to the `get_block_data` function in the `mpi_service`. This filter function removes from consideration all candidates from the MPI who are part of a person cluster containing a patient who satisfied blocking criteria, but which themselves have present values (i.e. are not missing fields) that disagree with incoming blocking keys. This will make matching more precise and reinforce validity in the blocking step.
#231 
N/A

Handle missing values in blocked MPI records

---

tests/performance/rlpt.env
tests/performance/scripts/send_linkage_requests.sh

Minor clean up to remove some old code in our performance testing suite that isn't being used.
[X-Use-Simple-Link was a header value](https://github.com/CDCgov/RecordLinker/pull/66) that was used for performance testing the differences between the phdi codebase and Record Linker.  This was [removed many months ago](https://github.com/CDCgov/RecordLinker/pull/68) when the phdi code was removed from the codebase, but we forgot to update the performance tests.

removing the unused SIMPLE_LINK parameter

---

.github/workflows/check_smoke_tests.yml
docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/assets/patient_bundle_to_link_with_mpi.json
tests/unit/assets/simple_patient_bundle_to_link_with_mpi.json
tests/unit/hl7/test_fhir.py
tests/unit/schemas/test_pii.py

This PR does two things:
1. Adds more robust-handling of two-digit date strings, so that dates like `02/09/39` parse as 1939 rather than 2039,
2. Adds validation that sets boundaries around acceptable dates by not accepting dates before 1850 and after the current day.
#237 
N/A

Parse and validate two-digit dates

---

src/recordlinker/hl7/fhir.py
src/recordlinker/schemas/pii.py
tests/unit/hl7/test_fhir.py
tests/unit/routes/test_patient_router.py
tests/unit/schemas/test_pii.py

Allowing for more than 1 race value to be specified per payload.  Also fixing a bug in the FHIR parser that only accepted the last race specified, now all race values are processed.
closes #250 

allowing multiple race values

---

.github/workflows/check_smoke_tests.yml

This PR addresses half of the caching issue outlined in ticket 224: ensuring that we use the cached the RecordLinker image when we run smoke tests to avoid hitting the limit on requests to DockerHub. 
After much tinkering, I added a `build-push-run` step to our smoke tests so now when you run them you should see that we use the image from ghcr for each smoke test instead of hitting `docker.io/library/python:3.12-slim` to build the service in each run.
Fixes #224 
Getting the services to run from images in the GHCR has proven to be much more difficult, which is why I opted to split up the work on #244. At least we will have cut down the number of requests for RecordLinker by the 4/1 deadline.
Please review …

Add caching of RecordLinker image to smoke tests

---

docs/site/reference.md
src/recordlinker/assets/initial_algorithms.json
src/recordlinker/linking/link.py
src/recordlinker/linking/matchers.py
src/recordlinker/models/algorithm.py
src/recordlinker/schemas/algorithm.py
tests/algorithm/configurations/algorithm_configuration.json
tests/unit/database/test_algorithm_service.py
tests/unit/linking/test_link.py
tests/unit/linking/test_matchers.py
tests/unit/routes/test_algorithm_router.py
tests/unit/schemas/test_algorithm.py

This PR adds more robust handling of comparisons between records in which one or more fields are missing data. If only a small amount of data is missing (fewer log-odds-worth than a specified percentage of the total possible), then missing comparisons are awarded partial weight to allow for data recovery and quality matches. However, if too much data is missing, the candidacy is automatically rejected.
Closes #235 
Just changed some variable names from the ticket for clarity

Handle missing fields during evaluation

---

src/recordlinker/routes/patient_router.py
src/recordlinker/routes/person_router.py

removing the hard-coded next url paths for our orphaned patient and person routes, and replacing with versions that are dynamically generated.  The work on the roadshow concept is requiring us to reorganize our API url paths, which will in effect change the path for both of these routes.  Doing this dynamically makes it easier to encapsulate all those url path changes in main.py.

dynamic next urls for patient/person routers

---

src/recordlinker/schemas/identifier.py
src/recordlinker/schemas/pii.py
tests/unit/schemas/test_algorithm.py
tests/unit/schemas/test_identifier.py
tests/unit/schemas/test_pii.py

Fix to address server errors when a null value is send for `race`, `identifier.type` or `address.line`.
closes #281 
Also fixing a broken test case from a bad merge.  https://github.com/CDCgov/RecordLinker/actions/runs/14340832961

bugfix for null values

---

src/recordlinker/assets/initial_algorithms.json
src/recordlinker/database/mpi_service.py
src/recordlinker/linking/link.py
src/recordlinker/models/mpi.py
src/recordlinker/routes/link_router.py
src/recordlinker/schemas/algorithm.py
src/recordlinker/schemas/pii.py
tests/algorithm/configurations/algorithm_configuration.json
tests/unit/conftest.py
tests/unit/database/test_mpi_service.py
tests/unit/linking/test_link.py
tests/unit/routes/test_link_router.py

Send a value of `schemas.Algorithm` and not `models.Algorithm` when linking records.
closes #294 
When we save the Algorithm configuration to the database, we store many values as strings (eg blocking keys, features, functions, etc).  However, when using the configuration during linkage, we prefer using the enum, functions and objects those strings represent. Previously, this meant we have to cast the string values to its native type in the link and compare methods.
By converting the model data back to a schema.Algorithm object, we can do that casting one time before the linkage process kicks off.  This helps simplify our linkage logic a bit as it no longer needs to worry about how to cast strings back to their native data types.
<--------------------- REMOVE THE LINES BELOW BEFORE …

Use schemas.Algorithm for linking

---

src/recordlinker/assets/suffixes.json
src/recordlinker/schemas/pii.py
tests/unit/schemas/test_pii.py

This changeset adds a pydantic validator that parses and normalizes suffixes according to a predefined mapping. I've left the mapping in an assets file in case we want to add roman numeral standardization at some later date.
Fixes #297 
I did some research on common suffixes in names in the US, and most results indicated it's pretty limited, just Junior, Senior, II, and III. It's easy to support roman numerals, as well as any other spelling or punctuated variants thereof, but given this I think leaving the suffixes we intend to support in an assets file (like with state abbreviations and street conventions) follows our established practice.
Please review and complete the following checklist before …

Add suffix normalization

---

docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/schemas/test_pii.py

This PR prepends normalized suffixes to first names during blocking. Following the convention of the existing `feature_iter` entry for First Name, only the first suffix is pulled, and _only_ if it has been normalized as a result of parsing. The least invasive way I found to make this change was an optional boolean flag on feature_iter proper, since otherwise in the blocking keys call we can't call feature_iter on First Name and have to basically repeat / reconstruct that code, but if that's preferable that's also okay with me.
Closes #298 

Prepend during blocking

---

src/recordlinker/assets/initial_algorithms.json
src/recordlinker/database/mpi_service.py
src/recordlinker/linking/link.py
src/recordlinker/linking/matchers.py
src/recordlinker/models/algorithm.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/algorithm.py
src/recordlinker/schemas/pii.py
tests/algorithm/configurations/algorithm_configuration.json
tests/unit/database/test_algorithm_service.py
tests/unit/database/test_mpi_service.py
tests/unit/linking/test_link.py
tests/unit/linking/test_matchers.py
tests/unit/routes/test_algorithm_router.py
tests/unit/schemas/test_algorithm.py

Create AlgorithmContext nested schema object to store include_multiple_results, log_odds and skip_values.
closes #293 
The `max_log_odds_points` parameter was removed from the compare method.  It's still required in the function, but now we need to retrieve the log_odds value for a feature BEFORE we call the matcher function (previously the matcher functions were retrieving this from the kwargs).  Since we're doing that in compare, it seemed simple enough to just make that a calculated value (summations are simple and quick).

schema.AlgorithmContext

---

src/api/recordlinker/routes/demo_router.py
src/api/recordlinker/session_store.py
tests/unit/conftest.py
tests/unit/routes/test_demo_router.py

This PR adds 2 new endpoints: 
1) "link" endpoint to update the `linked_status` to `True` when a user clicks on the "link" button. It also updates the `person_id` of the incoming record to match the `person_id` of the potential match record. The data is also stored in the session.
2) "unlink" endpoint to update the `linked_status` to `False` when a user clicks on the "unlink" button. It also updates the `person_id` of the incoming record to `null`. The data is also stored in the session.
For the data that is stored in the cookie session, I'm not sure if it is better just to save the boolean value of the linked status (what I've done) or if all the data is better. It seems like the values tend to be short but I'm looking for feedback/best practices! 
Closes #313 
I also removed the …

Add link and unlink endpoints

---

tests/algorithm/algo.env
tests/algorithm/data/nbs_seed.csv
tests/algorithm/data/nbs_test.csv
tests/algorithm/scripts/calculate_metrics.py
tests/algorithm/scripts/run_test.py
tests/algorithm/scripts/send_test_records.py

This PR is a fast-follow to a conversation had on 4/30 in which we established we wanted a standardized performance calculation script to be uploaded to our repo. This script integrates into the `run_test.py` script executed as part of algorithm tests, and gives us calculations for: raw counting stats (TP, FP, TN, FN), derived match quality stats (sens, spec, F1, PPV), and labels for matches graded possible by either system. This should standardize the way we calculate and report performance going forward.
**NOTE:** The change numbers look massive, but that's because we got the all-clear to upload our more robust test and seed data sets into the algorithm test configuration. There are only a couple changed code files, most of this is CSV uploading.
<--------------------- REMOVE THE LINES …

Add stats calculations and results display

---

src/recordlinker/linking/matchers.py
tests/unit/linking/test_link.py
tests/unit/linking/test_matchers.py

This PR adds the final piece of handling suffixes during name evaluation. Previously, we used them only during blocking, but this change set now includes handling during evaluation as well. In order to still maintain the First_Name field as its own readable entity, we've simply re-used the `should-prepend` parameter in `feature_iter`. That way, it's only during the very specific cases we've outlined that we combine a name and a suffix.
Closes #299 

Handle suffix during evaluation

---

compose.yml
src/ui/package-lock.json
src/ui/package.json
src/ui/src/app/layout.tsx
src/ui/src/app/match-queue/layout.tsx
src/ui/src/app/match-review/page.tsx
src/ui/src/app/match-review/recordView.tsx
src/ui/src/app/page.tsx
src/ui/src/components/serverError/serverError.module.scss
src/ui/src/components/toast/toast.tsx
src/ui/src/data/matchReview.ts
src/ui/src/styles/global.scss
src/ui/src/styles/uswds-customized.scss
src/ui/src/styles/variables.scss

This PR implements the link/unlink endpoints and the toast component. This work includes:
- Includes react-toastify dependency. Same library used in query connector.
- Integrates the toast component in the `root layout`.
- Implements a wrapper method to trigger the toast that takes care of the component customization with the uswds alert component.
- Clean up of the page-container classes. New implementation translates to less css lines after compilation.
- Adds styles in global for toastify classes.
Implements #317

Integrate link unlink endpoints

---

src/api/recordlinker/main.py

Static bundles should be served as gzip compressed assets whenever the browser accepts the format.
None
I briefly looked into how gzip compression can be supported and the only thing I was able to find was on the fly. I anyone knows a better way to setup this in FastAPI is greatly appreciate it.

Added gzip compression middleware

---

src/recordlinker/linking/link.py
src/recordlinker/schemas/link.py
tests/unit/linking/test_link.py

This PR adds feature median scores to the LinkResult class for purposes of data reporting. The feature medians are stored in a dictionary on the LinkResult so they can be accessed by feature name by a user who wishes to see how much of the total log odds points for a match came from a particular feature. Testing has been updated where relevant to verify feature medians are accurately generated for non-matches, matches, and missing information.
Closes #264 

Add feature medians

---

scripts/gen_seed_test_data.py

Somewhere in our updates to `PIIRecord`, we change the expectation for Race to a string. Faker produces a Race `object`, which I changed to a string so that we can continue to run `gen_seed_data.py`. 
Original error:
```
pii.py", line 411, in parse_race
return [Race.parse(v) for v in value]
^^^^^
TypeError: 'Race' object is not iterable
```
Fixes #359 
I'm guessing this script will be useful for jurisdictions testing out Record Linker so I wanted to make sure it stayed current.

Fix bug in scripts/gen_seed_data.py

---

src/recordlinker/schemas/algorithm.py
tests/unit/routes/test_algorithm_router.py

The algorithm context was never meant to be in the results of the listing API call, this call is supposed to just give high level details of what algorithms are available.  The specific detail API endpoints for each algorithm, should be used to get info on the algorithm context and/or the passes.

remove context from results in algorithm list

---

Dockerfile
scripts/bootstrap.sh
src/ui/package-lock.json
src/ui/package.json

While setting up the dibbs landing page I was able to fix the dependency tree and drop the legacy peer deps flag. This PR sets the correct versions for the dependencies triggering errors during `npm` install and removes the `--legacy-peer-deps` flag from the `npm install` commands. 
None

Fixes dependency tree

---

Dockerfile

Add a flag to uvicorn to allow proxy headers, specifically X-Forwarded-For and X-Forwarded-Proto, from the upstream server.  This will allow for SSL termination to happen upstream and any info necessary for Record Linker to be preserved in request headers. Which is necessary when setting a secure session cookie.
[Proxies and forwarded headers](https://www.uvicorn.org/deployment/#proxies-and-forwarded-headers)

Accept proxy headers

---

.github/workflows/trigger_demo_workflow.yaml

- Added a new GitHub Actions workflow file (trigger_demo_workflow.yaml) to enable manual deployment to the demo environment.
- The workflow accepts inputs for the service name and version, and triggers a secondary GitHub Actions workflow in `dibbs-tf-env`
- This initial PR is to test the permissions and integration with the `dibbs-tf-envs` repo. 
- I'll work directly with the team to customize the trigger as needed.
Once this merges to main:
- Manually trigger the workflow on GitHub.
- Verify that the API call is correctly made with the appropriate payload.
- Check the `dibbs-tf-envs` repo kicks off the appropriate job.

feat: add workflow to trigger deploy to demo environment

---

src/recordlinker/database/mpi_service.py
tests/unit/routes/test_patient_router.py

Allow for deleting a Patient record that as BlockingValues.
No cascade deletes are being used, so when attempting to delete a Patient record that also has BlockingValues in the database, a SQL error is raised.  Explicitly deleting those BlockingValues first, allows the Patient to be deleted.

bugfix: delete patient with keys

---

src/recordlinker/routes/tuning_router.py
src/recordlinker/tuning/base.py
tests/unit/routes/test_tuning_router.py

Fix tuning job timeout to properly cancel job if time is exceeded
closes #464
Using asyncio.wait_for will only timeout if the calling function yields control back to the caller, typically with some IO operation.  Tuning is heavily CPU bound, after the initial queries.  By converting the call to run the tuning operations in a separate thread, we can still enforce a timeout if the process takes too long.

fix tuning job timeout

---

src/recordlinker/database/mpi_service.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/algorithm.py
src/recordlinker/schemas/pii.py
src/recordlinker/schemas/tuning.py
src/recordlinker/tuning/base.py
src/recordlinker/tuning/prob_calc.py
tests/unit/database/test_mpi_service.py
tests/unit/tuning/test_prob_calc.py

Optimizing memory usage by ~70% in tuning calculations using iterators.
closes #456
- I couple of dataclasses were added to schemas/tuning to help with passing data between prob_calc and base.  TuningPair and TuningProbabilities.  The former is particularly helpful with a shift to iterators, as it's no longer possible to return values from the mpi_service queries.
- AlgorithmPass.resolved_label was added to help with type checks, as that guarantees a string will be returned (AlgorithmPass.label, could be null)
- Feature was configured to be "frozen" (meaning once a Feature object is instantiated, it can't be changed).  This is useful as we can now use them as keys in our log-odds dicts, rather than the feature string values as the keys.  This reduced the number of time we need to convert …

proc calc with iterators
