CDCgov/RecordLinker

ops/manifests/README
ops/manifests/record-linkage.yml
ops/manifests/scripts/minikube-start.sh

just a code migration
closes #21 

Migrate manifests files over to RL repo

---

.github/workflows/slack_notifier_merged.yaml
.github/workflows/slack_notifier_review.yaml

Notifies the #proj-cdc-idwa-dedupe-engineering channel whenever a pr is opened,reopened, or ready for review but never for drafts. Will also notify us when pr's a merged but not on closes before merges(merging this PR will officially test the on merge logic).
[Link any related issues or tasks from your project management system.]

[RL-25] Slack Notifications for reviews and merges

---

.github/workflows/slack_notifier_merged.yaml

fixing merge emoji for slack notifier
[Link any related issues or tasks from your project management system.]

Fix slack notifier merge emoji

---

src/recordlinker/linking/link.py
src/recordlinker/linking/matchers.py
src/recordlinker/models/mpi.py
src/recordlinker/models/pii.py
tests/unit/models/test_mpi.py
tests/unit/models/test_pii.py

Adding the ability to compare on address line and also create blocking keys on it.  Also making a few testing changes and fixing bugs to make the code ready for #24.
#24 
* Updated type annotations in `compare` function to use `models.Feature` instead of `models.FEATURE`. (`src/recordlinker/linking/link.py`)
* Changed the comparison result type from `bool` to `float` to allow for more granular matching results. (`src/recordlinker/linking/link.py`)
* Introduced a setter for the `data` property to update the internal state and clear the cached record. (`src/recordlinker/models/mpi.py`)
* Modified the `record` property and its setter to use `model_construct` for creating `PIIRecord` objects, enhancing data handling and validation. (`src/recordlinker/models/mpi.py`)
* Added `ADDRESS` as a new …

Add Address feature for comparisons

---

.github/workflows/check_unit_tests.yml
README.md

Publish unit test coverage to Codecov and show in README
https://app.codecov.io/github/CDCgov/RecordLinker
[Link any related issues or tasks from your project management system.]

RL-32 Publish test results and coverage to main README

---

Dockerfile

The ARG is LOG_CONFIG, not LOGGING_CONFIG

Bugfix for a ARG typo in the Dockerfile

---

.github/workflows/release.yml

Fixing the release job to properly delete the WIP release and create a new one.
fixes #108 

fix release job

---

tests/algorithm/data/sample_test_data.csv
tests/algorithm/scripts/helpers.py

Updating the helper script in the algorithm test suite to use multiple address lines per test.
Also adding a small fix to the sample test file to better match actual expected result values.

Multiple address lines in algorithm tests

---

pyproject.toml
src/recordlinker/log.py

Version 3 introduced changes to the module names and a few types. Updates have been made to recordlinker.log to support these changes.
closes #154 

upgrade python-json-logger to 3.X

---

scripts/local_server.sh
tests/unit/conftest.py
tests/unit/database/test_base.py

Auto delete unit testing artifacts post completion.
Also making a small fix to the local_server.sh script to run the source code in the src/ directory and not what has been installed into the virtualenv.

unit test cleanup

---

README.md

Slightly updates the README to better reflect the work needed for setting up on a Windows machine after setting up the repo on my desktop this morning. Also found a small typo that I fixed.
n/a
n/a

Slight tweaks to README for Windows set up & redoc typo

---

docs/site/design.md

Updating design.md with information about the id and reference_id values in the Patient and Person
tables, explaining the differences.

adding documentation about patient/person identifiers

---

docs/site/design.md

Adding a title and description to the ER diagram in site/design.md to improve accessibility.
https://mermaid.js.org/config/accessibility.html#accessible-title-and-description

Add ER diagram title and description

---

.github/workflows/check_types.yml

Removing tj-actions, it's not necessary for our mypy check, as it's ok to type check all the code.  This specifically addresses [CVE-2025-30066](https://www.cve.org/CVERecord?id=CVE-2025-30066)

upgrade tj-actions/changed-files

---

.github/workflows/check_smoke_tests.yml
docs/site/design.md
src/api/recordlinker/assets/initial_algorithms.json
src/api/recordlinker/linking/link.py
src/api/recordlinker/linking/matchers.py
src/api/recordlinker/models/algorithm.py
src/api/recordlinker/routes/link_router.py
src/api/recordlinker/schemas/__init__.py
src/api/recordlinker/schemas/algorithm.py
src/api/recordlinker/schemas/link.py
tests/algorithm/configurations/algorithm_configuration.json
tests/algorithm/scripts/send_test_records.py
tests/unit/assets/multiple_matches_patient_bundle.json
tests/unit/database/test_algorithm_service.py
tests/unit/linking/test_link.py
tests/unit/models/test_algorithm.py
tests/unit/routes/test_algorithm_router.py
tests/unit/routes/test_link_router.py
tests/unit/schemas/test_algorithm.py

PR brings latest main code into demo plus resolves merge conflicts.
None
None

Demo and Main sync (includes resolving merge conflicts)

---

docs/site/reference.md
src/recordlinker/schemas/pii.py
tests/unit/schemas/test_pii.py

Adding the NAME feature for matching.  Its primary use case will be for future skip values.
closes #234

NAME feature

---

.github/CODEOWNERS
.github/workflows/demo_package.yml

Workflow to publish docker images for the demo site to ghcr.io/cdcgov/recordlinker/demo when new commits are pushed to the demo branch.
closes #311
Also making Johanna a CODEOWNER for all changes in this branch.

demo packages

---

.github/workflows/check_smoke_tests.yml
docs/site/configuration.md
src/recordlinker/config.py
src/recordlinker/main.py
tests/unit/routes/test_seed_router.py
tests/unit/test_config.py
tests/unit/test_main.py

Adding a configuration setting to change the root path of the API
closes #287 

configurable API root path

---

src/recordlinker/database/algorithm_service.py
src/recordlinker/models/__init__.py
src/recordlinker/models/algorithm.py
tests/unit/database/test_algorithm_service.py
tests/unit/models/test_algorithm.py
tests/unit/routes/test_algorithm_router.py

Remove models.AlgorithmPass and store the data as a JSON list on the models.Algorithm
closes #292 

remove models.AlgorithmPass

---

src/ui/src/components/menu/menu.tsx

I realized that the algorithm configuration link is not aligned with the logo on the left so this code will fix that.
No issues!

Added flex styling to fix positioning of link

---

compose.yml
src/recordlinker/assets/initial_algorithms.json
tests/algorithm/configurations/algorithm_configuration.json

This PR defines some default skip values for the DIBBs algorithm and adds them to both the initial algorithm file and the file used for testing. It also updates the `compose` file that spins up the algorithm tests in docker, which was missing the `/api` addition when we configured the base URL.
Closes #333 

Define default skip values, update test data

---

.github/CODEOWNERS
.github/workflows/scan_trivy.yml
Dockerfile

Creating a job to scan the latest docker image in ghcr.io for vulnerabilities daily.  Scanning during building only partly solves the problem, as many of the vulnerabilities can be found after a release has already been shipped.

adding ghcr.io vulnerability scan job

---

.github/workflows/check_code_vulnerabilities.yml
src/recordlinker/assets/initial_algorithms.json
src/recordlinker/database/mpi_service.py
src/recordlinker/linking/link.py
src/recordlinker/linking/matchers.py
src/recordlinker/models/algorithm.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/algorithm.py
src/recordlinker/schemas/pii.py
tests/algorithm/configurations/algorithm_configuration.json
tests/unit/database/test_algorithm_service.py
tests/unit/database/test_mpi_service.py
tests/unit/linking/test_link.py
tests/unit/linking/test_matchers.py
tests/unit/routes/test_algorithm_router.py
tests/unit/schemas/test_algorithm.py

Create algorithm advanced section, `algorithm.context.advanced`, to store parameters that we advise users to change with caution.  All of these parameters will now come with recommended default values.
closes #296

Algorithm context advanced section

---

docs/site/configuration.md
docs/site/installation.md
src/recordlinker/main.py

Small changes to the site installation docs to help users get up and running faster.

minor installation doc changes

---

tests/algorithm/algo.env
tests/algorithm/data/expanded_nbs_test.csv
tests/algorithm/scripts/expand_test_data.py

This PR adds a script that allow us to combinatorially expand and scramble the test cases NBS provided for us. We leave each of the original test cases unchanged, but we generate a random number of duplicates of each case to mess with. We then dropout some fields to simulate missingness, as well as apply random likelihoods of edit distances to string values in algorithm-relevant fields. All of this is controlled by parameters at the top of the script (which only needs to be run once to make the data-set, doesn't need to be run each time we run the algorithm tests). Of note, the script right now copies the match decisions of the original test case into each duplicate we generate from it, no matter how much we then scramble and mangle the duplicate case. This is the reason we have poor …

Expand and scramble test cases

---

.github/workflows/check_smoke_tests.yml
docs/site/getting-started.md
scripts/example_linkage_test.sh
scripts/linkage_tests.sh

Scripting and enhancing (adding more steps to test API endpoints) the smoke test suite so its easy to run locally.  Also adding documentation to the site docs to give users an overview of how the API can be used.
closes #140 

enhanced smoke test and example usage

---

src/ui/src/app/page.tsx

Removing the where are we going section from the landing page.
The new landing page looks as follows

remove landing page where are we going section

---

scripts/gen_seed_test_data.py
tests/load/scrambler/config.py
tests/load/scrambler/json.py
tests/load/scrambler/utils.py
tests/load/scripts/scramble_data.py
tests/load/scripts/visualize_memory_usage.py

This PR updates the load testing scrambler to load and work on a single cluster at a time from a very large (~2GB) file of generated data. I used [`ijson`](https://github.com/ICRAR/ijson) to help with the incremental json loading, which fortunately allows us to read in each cluster individually and as a whole rather than in bytes at a time.  
To test this, I generated 1.5 million clusters (each with a single record) using the `gen_seed_data_script.py`. The resulting file was roughly 2GB (200MB when zipped). I then ran the scrambler on the unzipped version of the file and was able to sample and generate ~5 million scrambled records in 5 minutes on my local.  `python3 -m tests.load.scripts.scramble_data --file="./test_original_data.json" --max-seed-records 5000000`
Closes #387 
The next bit …

Implement incremental json loading

---

.github/CODEOWNERS
.github/workflows/trigger_demo_workflow.yaml

Removing the "system" input, as this workflow should only every deploy Record Linker code and not QC or ECRView code.  Also, changing the version input to build so users know to use a specific [demo docker image build tag](https://github.com/CDCgov/RecordLinker/pkgs/container/recordlinker%2Fdemo) from the following repo, and not a branch or release number.
Also removing Johanna from the CODEOWNERS file as she is moving to another team.

fix: small updates to trigger demo workflow

---

src/recordlinker/database/mpi_service.py

Speed optimizations to the `GET /api/person/orphaned` endpoint that results in ~17x improvement in query time.
Below is a comparison of the existing and optimized queries used to retrieve orphaned person clusters, along with the performance improvements achieved. The original query performed a join between every row in mpi_person and mpi_patient, which triggered a costly sequential scan of the entire mpi_patient table. In contrast, the optimized query uses a NOT EXISTS condition, allowing PostgreSQL to efficiently leverage indexes and quickly identify persons without any associated patient records.
```sql
SELECT mpi_person.id, mpi_person.reference_id
FROM mpi_person
LEFT OUTER JOIN mpi_patient ON mpi_patient.person_id = mpi_person.id
WHERE mpi_patient.id IS NULL
```
```sql
SELECT id, …
```

use not exists for orphaned persons query

---

pyproject.toml
scripts/gen_seed_test_data.py
tests/algorithm/scripts/set_configuration.py
tests/load/README.md
tests/load/assets/test_data.json
tests/load/locustfile.py

Adding more options to run load tests with, including the ability to toggle between `/link` and `/match`.
- adding missing load testing dependencies to pyproject.toml
- adding additional arguments to `scripts/gen_seed_test_data.py` to allow for data scrambling at creation time
- adding a load testing README.md

Add additional load test options

---

pyproject.toml
src/recordlinker/config.py
src/recordlinker/database/__init__.py
src/recordlinker/database/tuning_service.py
src/recordlinker/models/__init__.py
src/recordlinker/models/algorithm.py
src/recordlinker/models/tuning.py
src/recordlinker/schemas/__init__.py
src/recordlinker/schemas/tuning.py
src/recordlinker/splunk.py
src/recordlinker/utils/datetime.py
tests/unit/database/test_base.py
tests/unit/database/test_tuning_service.py
tests/unit/schemas/test_tuning.py
tests/unit/utils/test_datetime.py

Added `tuning_job` table and a few simple data access functions to facilitate creation, retrieval and updating.
closes #426
```mermaid
erDiagram
accTitle: Tuning Job Entity Relationship Diagram
accDescr: This diagram illustrates the TuningJob entity with its status enumeration values.
TuningJob {
uuid id PK "Primary Key (auto-generated)"
enum status "Status: PENDING, RUNNING, COMPLETED, FAILED"
json params "Tuning Parameters JSON Object"
json results "Tuning Results JSON Object"
datetime started_at "Job Start Timestamp"
datetime finished_at "Job Completion Timestamp (nullable)"
}
```
- Adding a tuning feature flag to easily enable/disable this work. Currently, when disabled this just skips creating the "tuning_job" table, but in the future we can remove the tuning API endpoints when …

tuning schema

---

src/recordlinker/schemas/tuning.py
src/recordlinker/tuning/base.py

This PR adds the algorithm label to the PassRecommendation schema so that it is returned in the model dump of a tuning response.
Closes #459 

Add algorithm label to pass recs

---

src/recordlinker/database/mpi_service.py
src/recordlinker/tuning/base.py
tests/unit/routes/test_tuning_router.py

This PR adds error handling and logger processing for a variety of issues that could be present in the MPI that might stop tuning from working properly. DB cluster structured is validated, as are request params.
#455 

Add robustness error processing

---

docs/mkdocs.yml
docs/site/app-configuration.md
docs/site/tuning.md
scripts/build_docs.sh

Updating the site docs with usage and background information on tuning.

tuning site docs
